Clarify schedule
StudieverenigingSTORM/BAPC21-site pull request #19
Opened 2021-05-10 08:52 UTC by iMylene

2021-05-10 08:56 UTC, mvr320 requested changes
GHA fails.

2021-05-12 20:47 UTC, mvr320 commented on content/schedule.md
> +| June      | Announcement preliminaries dates                          |
```suggestion
| June      | Announcement of preliminaries date                           |
```

2021-05-12 20:48 UTC, mvr320 commented
@iMylene can you squash this?

2021-05-12 20:49 UTC, mvr320 requested changes
Can you squash and make it 1 prelim date?

2021-05-13 12:58 UTC, EuiYeonJang commented
> Can you squash and make it 1 prelim date?
I'm confused as to what this is referring?

2021-05-13 13:08 UTC, mvr320 commented
It was for Mylène to make this PR have 1 commit,


And instead of multiple dates we should have 1 proposal date, and hope that everyone can do that date.

On 13 May 2021, at 14:58, EuiYeonJang ***@***.******@***.***>> wrote:


Can you squash and make it 1 prelim date?
I'm confused as to what this is referring?

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub<https://github.com/StudieverenigingSTORM/BAPC21-site/pull/19#issuecomment-840537594>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ADRSWMZFFVJKONTG5YE36M3TNPEHVANCNFSM44QUOAXA>.

2021-05-13 16:48 UTC, mvr320 approved these changes

2021-05-13 16:53 UTC, merged