Options for contact: mail and Slack
StudieverenigingSTORM/BAPC21-site pull request #23
Opened 2021-05-15 08:11 UTC by iMylene

2021-05-15 08:56 UTC, mvr320 commented on content/contact.md
> -***Slack*** - The community created a [BAPC Slack](https://benelux-nwerc.slack.com/). Feel free to reach out to us on the *#general* channel in the Slack. For access, visit [this link](https://bapc-s
```suggestion
***Slack*** - The BAPC community maintains a [Slack](https://benelux-nwerc.slack.com/). Feel free to reach out to us on the *#general* channel in the Slack. For access, visit [this link](https://bapc-slack-enroll.herokuapp.com) with token `I heart Benelux`. Questions on how to organize a preliminary, help with the ICPC system or general help can be asked here.
```

2021-05-15 13:45 UTC, mvr320 commented on content/contact.md
> +***Slack*** — The BAPC community maintains a [Slack](https://benelux-nwerc.slack.com/). Feel free to reach out to us on the *#general* channel in the Slack. For access, visit [this link](https://bapc
```suggestion
***Slack*** — The BAPC community maintains a [Slack](https://benelux-nwerc.slack.com/). Feel free to reach out to us on the *#general* channel in the Slack. For access, visit [this link](https://bapc-slack-enroll.herokuapp.com) with token `I heart Benelux`. Questions on how to organize a preliminary, help with the ICPC system or general help may be asked here.
```

2021-05-17 12:58 UTC, mvr320 commented on content/contact.md
> +***Mail*** — You can drop us an email at: *organization “at” BAPC “dot” EU*.
Move this one down?

And than tell people this is the less preferred alternative?

2021-05-17 12:58 UTC, mvr320 requested changes
Move the mail one down?

And than tell people this is the less preferred alternative?

2021-05-17 13:15 UTC, mvr320 reviewed
Looks fine, if someone else also agrees this can be merged!

2021-05-17 13:19 UTC, EBaalhuis reviewed
looks good

2021-05-17 14:20 UTC, mvr320 approved these changes

2021-05-17 19:10 UTC, merged