Diversity rules draft
StudieverenigingSTORM/BAPC21-site pull request #29
Opened 2021-07-09 08:29 UTC by shanemin

2021-07-09 09:05 UTC, mvr320 requested changes

2021-07-09 09:05 UTC, mvr320 commented on content/rules.md
> +Coaches and teams participating in the BAPC are urged to read the official Code of Conduct \ref{CoC}. Discrimination of any kind will not be tolerated during the contest, and may be grounds for disqu
For now I would remove the line about the Code of Conduct as its not there yet (and breaks the pipeline)

I agree that we should have that in the future.
```suggestion
Discrimination of any kind will not be tolerated during the contest, and may be grounds for disqualification at the discretion of the Contest Director.
```

2021-07-09 11:11 UTC, EuiYeonJang commented on content/rules.md
> +  - Maximum of 2 additional slots awarded
Just a clarification question, is in addition to the slot awarded above (therefore a total of 3 additional can be earned) or in total, max 2 slots can be awarded ?

2021-07-09 11:12 UTC, EuiYeonJang commented on content/rules.md
> +  - The BAPC organizing committee determines the number of slots on a per-institution basis
I would change the order of these two sub-bullet points

2021-07-12 17:49 UTC, mvr320 approved these changes

2021-07-12 19:14 UTC, EuiYeonJang approved these changes

2021-07-12 19:14 UTC, merged